#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuentrame.Tests.EmailTests
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class TestTemplate : Encuentrame.Support.Email.Templates.BaseTemplate             
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



            
            #line 6 "..\..\EmailTests\TestTemplate.cshtml"
Write(Model.Text);

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
