#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuentrame.Support.Email.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class ObjectCreatedTemplate : Encuentrame.Support.Email.Templates.BaseTemplate
    {
#line hidden

        public override void Execute()
        {

WriteLiteral("\r\n<html>\r\n<head>\r\n    <title>");


            
            #line 5 "..\..\Templates\ObjectCreatedTemplate.cshtml"
      Write(Model.ObjectTypeCreated);

            
            #line default
            #line hidden
WriteLiteral(" fue creado.</title>\r\n</head>\r\n<body>\r\n    <h2>El usuario ");


            
            #line 8 "..\..\Templates\ObjectCreatedTemplate.cshtml"
              Write(Model.UserName);

            
            #line default
            #line hidden
WriteLiteral(" creo ");


            
            #line 8 "..\..\Templates\ObjectCreatedTemplate.cshtml"
                                   Write(Model.ObjectTypeCreated);

            
            #line default
            #line hidden
WriteLiteral(": ");


            
            #line 8 "..\..\Templates\ObjectCreatedTemplate.cshtml"
                                                             Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
