#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuentrame.Support.Email.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class WelcomeUserTemplate : Encuentrame.Support.Email.Templates.BaseTemplate
    {
#line hidden

        public override void Execute()
        {

WriteLiteral("\r\n<html>\r\n<head>\r\n    <title>Bienvenido</title>\r\n</head>\r\n<body>\r\n    <h2>Bienven" +
"ido ");


            
            #line 8 "..\..\Templates\WelcomeUserTemplate.cshtml"
              Write(Model.Username);

            
            #line default
            #line hidden
WriteLiteral(" a ");


            
            #line 8 "..\..\Templates\WelcomeUserTemplate.cshtml"
                                Write(Model.Site);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n    <p>");


            
            #line 9 "..\..\Templates\WelcomeUserTemplate.cshtml"
  Write(Model.WelcomeInstructions);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
